version: "3.8"
services:
  # backend:
  frontend:
    image: roeika/plomo-vite:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    # depends_on:
    # - backend
